name: Embedded targets

on:
  push:

jobs:
  linux:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Cross script
      run: |
            which rustup || curl https://sh.rustup.rs -sSf | sh -s -- -y
            rustup update

            . $HOME/.cargo/env

            rustc --version

            sudo apt-get -y update
            sudo apt-get -y install binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu libssl-dev pkg-config
            rustup target add aarch64-unknown-linux-gnu

            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            cargo build -vvv --target aarch64-unknown-linux-gnu --release

